[config]
dataset = "cifar10" # [cifar10, mnist]
model = "vit" # [vit]
batch_size = 128
precision = "bf16-mixed" # [16-mixed, bf16-mixed, 32-true]
task = "mae" # [classification, reconstruction, mae]
masking_fraction = 0.85
strategy = "fsdp" # [ddp, fsdp, ddp_find_unused_parameters_true, deepspeed_stage_3]
epochs = 30
accelerator = "gpu"
gpus = 1
load_ckpt = ""
data_dir = "/scratch/gpfs/js5013/data/ml/"
train = true
nshot = 0 # 0 for full training data
compile = false
