[config]
dataset = "cifar10" # [cifar10, mnist, imagenet]
model = "vit" # [vit]
embed_dim = 512
mlp_ratio = 4
num_blocks = 10
num_heads = 16
decoder_num_blocks = 2
batch_size = 512
precision = "bf16-mixed" # [16-mixed, bf16-mixed, 32-true]
task = "classification" # [classification, reconstruction, mae]
masking_fraction = 0.2
strategy = "ddp_find_unused_parameters_true" # [ddp, fsdp, ddp_find_unused_parameters_true, deepspeed_stage_3]
epochs = 40
accelerator = "gpu"
gpus = 2
load_ckpt = ""
data_dir = "/scratch/gpfs/js5013/data/ml/"
train = true
nshot = 0 # 0 for full training data
compile = false
