[config]
dataset = "mnist" # [cifar10, mnist, imagenet, galaxy10, galaxy10decals]
model = "mae" # [mae, vit]
model_path = "../train/lightning_logs/version_1034838/checkpoints/epoch=29-step=28140.ckpt"
batch_size = 64
precision = "bf16-mixed" # [16-mixed, bf16-mixed, 32-true]
task = "classification" # [classification, reconstruction]
strategy = "ddp" # [ddp, fsdp, ddp_find_unused_parameters_true, deepspeed_stage_3]
epochs = 50
accelerator = "gpu"
gpus = 1
load_ckpt = ""
data_dir = "/scratch/gpfs/js5013/data/ml/"
train = true
nshot = 0 # 0 for full training data
